import Foundation
import LGNLog
import Yams

typealias Dict = [(String, Any)]

enum E: Error {
    case InvalidSchema(String)
}

extension E: CustomStringConvertible {
    var description: String {
        let result: String

        switch self {
        case .InvalidSchema(let error): result = "InvalidSchema: \(error)"
        }

        return result
    }
}

protocol AnyBuilder {
    typealias Schema = (shared: Shared, services: [(String, Service)])

    var compiledSchemaFilename: String { get }
    var inputDirectory: URL { get }
    var outputDirectory: URL { get }
    var services: [String] { get }
    var dryRun: Bool { get }
    var emitRawSchema: Bool { get }
    var emitProcessedSchema: Bool { get }

    init(
        inputDirectory: URL,
        outputDirectory: URL,
        services: [String],
        dryRun: Bool,
        emitRawSchema: Bool,
        emitProcessedSchema: Bool
    ) throws
    func build() throws
    func generateCore(from schema: Schema) throws -> String
    func generate(service: Service, shared: Shared) throws -> String
}

fileprivate extension URL {
    func path(_ prefix: URL) -> String {
        self.path.replacingOccurrences(of: prefix.path + "/", with: "")
    }
}

fileprivate class Leaf {
    private var storage: [Substring: Leaf] = [:]

    func has(_ string: Substring) -> Bool {
        self.get(string) != nil
    }

    func get(_ string: Substring) -> Leaf? {
        self.storage[string]
    }

    func createEmpty(_ string: Substring) {
        self.storage[string] = Leaf()
    }
}

extension AnyBuilder {
    var compiledSchemaFilename: String {
        "result.yml"
    }

    func build() throws {
        // let profiler = Profiler.begin()

        let inputFiles: [URL] = try self
            .getFilesUnder(directory: self.inputDirectory, extensions: ["yml", "yaml"])
            .filter { $0.lastPathComponent != self.compiledSchemaFilename }
            .sorted(by: { $0.path.lowercased() < $1.path.lowercased() })

        Logger.current.debug("Found \(inputFiles.count) files")

        let yaml = try self.buildCompleteSchema(
            from: []
                + inputFiles.filter({ $0.path(self.inputDirectory).starts(with: "Shared/") })
                + inputFiles.filter({ !$0.path(self.inputDirectory).starts(with: "Shared/") })
        )

        let schema = try self.parse(yaml: yaml)

        try self.generateCode(from: schema)

        // TODO: validate custom fields and other Shared references 
    }

    fileprivate func buildCompleteSchema(from URLs: [URL], filename: String? = nil) throws -> Any? {
        //let filename = filename ?? self.compiledSchemaFilename
        let root = "__root__"
        let indent = "  "
        let EOL = "\n"

        let tree = Leaf()
        var result = ""

        for file in URLs {
            let shortFilename = file.path(self.inputDirectory)
            var level: Int = 0
            var leaf = tree
            var contents = try String(contentsOf: file, encoding: .utf8)
            var parts = shortFilename.replacingOccurrences(of: ".yml", with: "").split(separator: "/")

            if parts.count >= 5 && parts[0] == "Services" && parts[2] == "Contracts" {
                let path = Substring(parts[3...].joined(separator: "/"))
                parts = parts[0...2] + [path]
                contents = "ForcedURI: \"\(path)\" # autogenerated\(EOL)\(EOL)\(contents)"
            }
            for (i, part) in parts.enumerated() {
                if part != root && !leaf.has(part) {
                    leaf.createEmpty(part)
                    result += .init(repeating: indent, count: level) + part + ":\(EOL)"
                }
                if i + 1 == parts.count {
                    let _indent: String = .init(repeating: indent, count: part != root ? level + 1 : level)
                    result += "\(_indent)# BEGIN \(shortFilename)\(EOL)"
                    result += contents
                        .split(separator: Character(EOL))
                        .map { _indent + $0 }
                        .joined(separator: EOL) + EOL
                    result += "\(_indent)# END \(shortFilename)\(EOL)"
                } else {
                    leaf = leaf.get(part)!
                    level += 1
                }
            }
        }

        if self.emitRawSchema {
            print(result)
            exit(0)
        }

        let parsed: Node = try Yams.compose(yaml: result, .default, .dictionaryAsPairs) ?? Node.scalar(.init(""))

        if self.emitProcessedSchema {
            try print(
                Yams.serialize(
                    node: parsed,
                    canonical: false,
                    indent: 2,
                    //width: <#T##Int#>,
                    allowUnicode: true,
                    lineBreak: .ln,
                    //explicitStart: <#T##Bool#>,
                    //explicitEnd: <#T##Bool#>,
                    //version: <#T##(major: Int, minor: Int)?#>,
                    sortKeys: false
                )
            )
            exit(0)
        }

        return parsed.any
    }

    fileprivate func getFilesUnder(directory: URL, extensions: [String]) throws -> [URL] {
        let manager = FileManager.default
        var result = [URL]()

        for url in try manager.contentsOfDirectory(at: directory, includingPropertiesForKeys: [.isDirectoryKey]) {
            if try url.resourceValues(forKeys: [.isDirectoryKey]).isDirectory == true {
                try result.append(contentsOf: self.getFilesUnder(directory: url, extensions: extensions))
            } else if extensions.contains(url.pathExtension) {
                result.append(url)
            }
        }

        return result
    }

    fileprivate func parse(yaml: Any?) throws -> Schema {
        Logger.current.debug("Parsing schema")

        guard let root = yaml as? Dict else {
            throw E.InvalidSchema("Schema does not contain root")
        }

        guard let rawServices = root["Services"] as? Dict else {
            throw E.InvalidSchema("Schema does not contain services")
        }

        var servicesNames: Set<String> = []
        for (serviceName, _) in rawServices {
            if self.services.count > 0 && !self.services.contains(serviceName) {
                continue
            }
            guard !servicesNames.contains(serviceName) else {
                throw E.InvalidSchema("Service '\(serviceName)' is defined more than once (must be unique)")
            }
            servicesNames.insert(serviceName)
        }

        let shared: Shared = try .init(from: root["Shared"] as? Dict ?? [])

        return (
            shared: shared,
            services: try rawServices
                .filter { serviceName, _ in servicesNames.contains(serviceName) }
                .map { serviceName, rawService in
                    (serviceName, try Service(name: serviceName, from: rawService, shared: shared))
                }
        )
    }

    fileprivate func generateCode(from schema: Schema) throws {
        let generatedCore = try self.generateCore(from: schema)
        let fileCore = URL(fileURLWithPath: "Core.swift", relativeTo: self.outputDirectory)
        if !self.dryRun {
            try generatedCore.write(
                to: fileCore,
                atomically: true,
                encoding: .utf8
            )
        }
        Logger.current.info("Successfully written core to \(fileCore.absoluteString)")

        let fullServicesList: [String] = schema.services.map { name, _ in name }
        let desiredServicesList = self.services.isEmpty ? fullServicesList : self.services
        for serviceName in desiredServicesList {
            guard let service = schema.services.first(where: { $0.0 == serviceName })?.1 else {
                throw E.InvalidSchema(
                    "Requested service '\(serviceName)' not present in schema (\(fullServicesList))"
                )
            }
            let generatedService = try self.generate(service: service, shared: schema.shared)
            let fileService = URL(fileURLWithPath: "Service\(serviceName).swift", relativeTo: self.outputDirectory)
            if !self.dryRun {
                try generatedService.write(
                    to: fileService,
                    atomically: true,
                    encoding: .utf8
                )
            }
            Logger.current.info("Successfully written service '\(serviceName)' to \(fileService.absoluteString)")
        }
    }
}
